title: DJblog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/DJblog" # the subpath of your site, e.g. /blog
url: "http://djyun.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Dongjun Yun # add your name
author-img: DongjunYun.jpg # add your photo
about-author: I am Data Scientist on Marketing. Always analyze data and modeling with curiosity for FUN. # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: djyunn# add your Github handle
social-linkedin: in/dongjun-yun-77a397157/# add your Linkedin handle
social-email: ydj9398@naver.com# add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
